
on:
  push:
    branches:
    - master

jobs:
  build_and_test:
    name: Build and test lognplot rust library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: cargo build --release -p lognplot
      - run: cargo test -p lognplot

  windows_build:
    name: Build on windows
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup msys2 environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gtk3 mingw-w64-x86_64-hdf5
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Build rust code
        run: cargo build --release -p lognplotgtk -p lognplot -p clognplot
      - name: Archive executable
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: target/release/*.exe
