
on:
  push:
    branches:
    - master

jobs:
  build_and_test:
    name: Build and test lognplot rust library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - run: cargo build --release -p lognplot
      - run: cargo test -p lognplot

  windows_build:
    name: Build on windows (MINGW64/GNU build)
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup msys2 environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gtk3 mingw-w64-x86_64-hdf5
      - name: Patch HDF5 dll for hdf5 crate
        run: |
          Copy-Item D:\a\_temp\msys64\mingw64\bin\libhdf5-0.dll -Destination D:\a\_temp\msys64\mingw64\lib\hdf5-0.dll
          echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-gnu
          profile: minimal
      - name: Build rust code
        env:
          HDF5_DIR: D:\a\_temp\msys64\mingw64
        run: cargo build --release -p lognplotgtk --no-default-features
      - name: Archive executable
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: target/release/*.exe
